[build]
  functions = "netlify/functions"   # ระบุที่ที่ Netlify ควรมองหาฟังก์ชัน
  publish = "public"  # ระบุโฟลเดอร์ที่มีไฟล์ static (เช่น index.html)

[[redirects]]
  from = "/shorten"
  to = "/.netlify/functions/shorten"
  status = 200
  force = true

[[redirects]]
  from = "/{shortUrl}"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
