[build]
  functions = "netlify/functions"   # ระบุที่ที่ Netlify ควรมองหาฟังก์ชัน
  publish = "public"  # ระบุโฟลเดอร์ที่มีไฟล์ static (เช่น index.html)

[[redirects]]
  from = "/script"
  to = "/.netlify/functions/script"
  status = 200
  force = true
